backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tools Used", name: "tools", widget: "list" }
      - { label: "Project Images", name: "gallery", widget: "list", field: {label: Image, name: image, widget: image} }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "about"
    label: "About Me"
    files:
      - file: "content/about.md"
        label: "About Section"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Bio", name: "body", widget: "markdown" }
          - { label: "Profile Image", name: "profile_image", widget: "image" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Name", name: "name", widget: "string" }
      - { label: "Feedback", name: "feedback", widget: "text" }
      - { label: "Client Photo", name: "photo", widget: "image", required: false }
